"""empty message

Revision ID: 44c5818ae2c1
Revises: 
Create Date: 2024-07-24 11:45:09.505269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44c5818ae2c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('distance', sa.String(), nullable=False),
    sa.Column('num_sites', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('clue', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('user_input_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_input_id'], ['user_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('user_input')
    # ### end Alembic commands ###
