"""empty message

Revision ID: 6ba8cd08c6fa
Revises: 
Create Date: 2024-07-01 16:26:08.621656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba8cd08c6fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('distance', sa.String(), nullable=False),
    sa.Column('num_sites', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('clue', sa.String(), nullable=False),
    sa.Column('user_input_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_input_id'], ['user_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('user_input')
    # ### end Alembic commands ###
