"""empty message

Revision ID: c3d8d86c58dd
Revises: 
Create Date: 2024-07-25 20:04:10.064757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3d8d86c58dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_latitude', sa.String(), nullable=False),
    sa.Column('start_longitude', sa.String(), nullable=False),
    sa.Column('distance', sa.String(), nullable=False),
    sa.Column('num_sites', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('clues', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('hunt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hunt_id'], ['hunt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('hunt')
    # ### end Alembic commands ###
